### ISSUE TITLE
how to fetch External API call

### ISSUE THREAD

**Issue by jeblister** [hyperfuse/micro-rest#2]
Hi,
I try to fetch external data using this handler : 
`file: /src/controllers/api.js`
```js
const axios = require('axios')

function getUserAccount() {
    axios.get('https://api.github.com/users/github')
        .then(function (data) {
            return data.json()
        })
        .catch(function (error) {
            return error
        })
}


export default getUserAccount
```
but i got this response : 
```
{
message: "GET /api not found"
}
```

Whats wrong with my code?

**Comment by kennetpostigo** [comment]
Hey @jeblister ,  are you adding it into index.js?

**Comment by jeblister** [comment]
Hey @kennetpostigo, no i create a file here `/src/controllers/api.js` for that and import this module in `index.js`

**Comment by kennetpostigo** [comment]
Do you have your project on github?

**Comment by jeblister** [comment]
No. but i can push it to github.

**Comment by kennetpostigo** [comment]
Please do and link to it when you can :)

**Comment by jeblister** [comment]
It there https://github.com/jeblister/micro-rest

**Comment by kennetpostigo** [comment]
Can you add a log statement from the axios call and then hit the route?
```js
function getUserAccount() {
    axios.get('https://api.github.com/users/github')
        .then(function (data) {
            console.log(data.json())
            return data.json()
        })
        .catch(function (error) {
            console.log(error)
            return error
        })
}
```

Also I'm not sure you will get anything return value from that call.
type this in the chrome console: 
```js
fetch('https://api.github.com/users/github').then(res => res);
```
The return value is: 
```js
Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
```
However when you do:
```js
fetch('https://api.github.com/users/github')
.then(res => console.log(res));
```
You will get back:
```js
Response {type: "cors", url: "https://api.github.com/users/github", status: 200, ok: true, statusText: "OK"…}
```

**Comment by jeblister** [comment]
I got this error message `ReferenceError: XMLHttpRequest is not defined`

**Comment by kennetpostigo** [comment]
Are you using a bundler of any kind? That looks to me like an issue with axios not really anything related to micro-rest. XMLHttpRequest is a web api browsers provide. I don't believe nodejs has this API.

**Comment by jeblister** [comment]
No. I just clone `hyperfuse/micro-rest` repo and add `axios` and install dependencies with `yarn`.

Is there another approach to fetch External API call with [micro](https://github.com/zeit/micro) ?

**Comment by kennetpostigo** [comment]
Yea, I really don't think this is a problem with micro-rest. I think this is coming from axios. Micro rest does not use XMLHTTPRequest at all. You could try isomorphic-fetch which I know works but you can't just return unresolved promises either like you were doing above. You need to return data.

**Comment by jeblister** [comment]
Hi @kennetpostigo,
Yes you're right, the problem is coming from axios, it does not support Promise . and `isomorphic-fetch` too.
I resolve this problem after using `[Request-Promise](https://github.com/request/request-promise)` a simplified HTTP request client with Promise support.

**Comment by kennetpostigo** [comment]
Nice! Is this good to close now?

**Comment by jeblister** [comment]
Yes. Thank you.
